apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}-config"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  APP_ENV: {{ .Values.env.APP_ENV }}
  APP_VERSION: {{ .Values.env.APP_VERSION  }}